### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by saikatkoley** [ATM-Consulting/dolibarr_module_servicerestaurant#3]
I was trying to install in Dolibarr 6 and Dolibarr 9 but it's showing an error that is "Error Incorrect integer value: '' for column 'usertype' at row 1" and a warring "Jeu d'essai déjà existant" also i can see it has not any sql folder so how it will create it's table in database after installing? Please help i just wanted to explore this module.

**Comment by aconits** [comment]
Hi @saikatkoley 

This module was developped by students to teach them and this module is not completly fonctionnal
Your error  looks like a postgres sql error by inserting integer value as string

You can fork this module and resume developing because we will don't anymore

Enjoy! :smile:
