### ISSUE TITLE
Bug Error Incorrect integer value: '' for column 'usertype' at row 1

### ISSUE THREAD

**Issue by webmasterproxy-media** [ATM-Consulting/dolibarr_module_servicerestaurant#5]
Bjr

Lorsque que je veux activer le module

Error Incorrect integer value: '' for column 'usertype' at row 1

Jeu d'essai déjà existant

Dolibarr v7 v8 v 9 v10

**Comment by aconits** [comment]
Voir #3

**Comment by webmasterproxy-media** [comment]
Vu apres desolé
